# Generated by Django 4.2.1 on 2023-05-14 15:58

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='Firstname')),
                ('lastname', models.CharField(max_length=255, verbose_name='Lastname')),
                ('gender', models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], max_length=10, verbose_name='Gender')),
                ('blood_type', models.CharField(max_length=100, verbose_name='Blood type')),
                ('is_jobless', models.BooleanField(blank=True, null=True, verbose_name='Is jobless')),
                ('is_married', models.BooleanField(default=False, verbose_name='Is married')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('postal_code', models.IntegerField(verbose_name='Postal code')),
                ('address', models.TextField(verbose_name='Address')),
                ('registered', models.CharField(max_length=255, verbose_name='Registered name')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.person', verbose_name='Person ID')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Action description')),
                ('estimation', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Act estimation')),
                ('date', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='Date act')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.person', verbose_name='Person')),
            ],
        ),
    ]
